version: "3.1"

services:
  daedalus_db:
    image: postgres
    container_name: daedalus
    environment:
      POSTGRES_USER: lucid
      POSTGRES_PASSWORD: lucid
      POSTGRES_DB: daedalus
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 512M

  daedalus_redis:
    image: redis:alpine
    container_name: daedalus_redis
    command: redis-server --requirepass lucid
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          memory: 512M
